apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "mongoshake-prometheus-exporter.fullname" . }}
  labels:
    {{- include "mongoshake-prometheus-exporter.labels" . | nindent 4 }}
spec:
  endpoints:
  - port: http
    path: /metrics
    interval: 15s
  selector:
    matchLabels:
      {{- include "mongoshake-prometheus-exporter.selectorLabels" . | nindent 6 }}
